### PR TITLE
 Update CircleCI orbs

### PR DESCRIPTION
**Pull request by alysbrooks**
This is a pretty safe change, but I haven't touched the CircleCI configuration before, so making it a PR just in case.

### CODE REVIEW

**Comment by plexus** [comment]
Same issue here. Going to chalk this up to either a github or a circle glitch.

**Comment by alysbrooks** [comment]
Looks like the other repositories have a deploy key for CircleCI, but this one doesn't. I think that's the problem?

**Comment by plexus** [comment]
I re-did the CircleCI setup and triggered the build for this PR again manually. I've also enabled CircleCI for some projects that had a `.circleci` config but weren't actually building yet (fetch, ansi, kaocha-cljs2, funnel, chui).

**Comment by plexus** [comment]
Yay! We got it to go green 💚

**Comment by plexus** [comment]
bump_it

**Pull request merged**
